name: Android Pull Request CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check ktlint format
        run: ./gradlew ktlintCheck

      # Run unit test
      - name: Run unit test
        run: ./gradlew testDebugUnitTest
